VisionRestaurant/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using VisionRestaurant.Data;
using VisionRestaurant.Model;

namespace VisionRestaurant.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly VisionRestaurantContext _db;
        private readonly UserManager<ApplicationUser> _UserManager;
        public IList<CheckoutItems> Items { get; private set; }
        public OrderHistory Order = new OrderHistory();

        public decimal Total = 0;
        public long AmountPayable = 0;

        public CheckoutModel(VisionRestaurantContext db,UserManager<ApplicationUser> UserManager)
        {
            _db = db;
            _UserManager = UserManager;
        }

        public async Task OnGetAsync()
        {
            var user = await _UserManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db
            .CheckoutCustomers
            .FindAsync(user.Email);

            Items = _db.CheckoutItems.FromSqlRaw(
                "SELECT Food.ID, Food.Price, " +
                "Food.Name, " +
                "BasketItems.BasketID, BasketItems.Quantity " +
                "FROM Food INNER JOIN BasketItems " +
                "ON Food.ID = BasketItems.ID " +
                "WHERE BasketID = {0}", customer.BasketID
                ).ToList();
            Total = 0;
            foreach (var item in Items)
            {
                Total += (item.Quantity * item.Price);
            }
            AmountPayable = (long)(Total * 100);

        }
        public async Task<IActionResult> OnPostBuyAsync()
        {
            var currentOrder = _db.OrderHistories.FromSqlRaw("SELECT * From OrderHistories")
                .OrderByDescending(b => b.OrderNo)
                .FirstOrDefault();

            if (currentOrder == null)
            {
                Order.OrderNo = 1;
            }
            else
            {
                Order.OrderNo = currentOrder.OrderNo + 1;
            }

            var user = await _UserManager.GetUserAsync(User);
            Order.Email = user.Email;
            _db.OrderHistories.Add(Order);

            CheckoutCustomer customer = await _db
                .CheckoutCustomers
                .FindAsync(user.Email);

            var basketItems =
                _db.BasketItems
                .FromSqlRaw("SELECT * From BasketItems " +
                "WHERE BasketID = {0}", customer.BasketID)
                .ToList();

            foreach (var item in basketItems)
            {
                OrderItem oi = new OrderItem
                {
                    OrderNo = Order.OrderNo,
                    ID = item.ID,
                    Quantity = item.Quantity
                };
                _db.OrderItems.Add(oi);
                _db.BasketItems.Remove(item);
            }

            await _db.SaveChangesAsync();

            return RedirectToPage("/Index");
        }


    }
}

VisionRestaurant/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using System.Net;
using VisionRestaurant.Model;

namespace VisionRestaurant.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public EmailModel Input { get; set; }
        public string Message { get; set; }

        private IConfiguration Configuration;

        public ContactModel(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        public IActionResult OnPost()
        {
            //Read SMTP settings from AppSettings.json.
            string host = this.Configuration.GetValue<string>("Smtp:Server");
            int port = this.Configuration.GetValue<int>("Smtp:Port");
            string fromAddress = this.Configuration.GetValue<string>("Smtp:FromAddress");
            string userName = this.Configuration.GetValue<string>("Smtp:UserName");
            string password = this.Configuration.GetValue<string>("Smtp:Password");

            using (MailMessage mm = new MailMessage(fromAddress, "admin@aspsnippets.com"))
            {
                mm.Subject = Input.Subject;
                mm.Body = "Name: " + Input.Name + "<br /><br />Email: " + Input.Email + "<br />" + Input.Body;
                mm.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = host;
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(userName, password);
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = port;
                    smtp.Send(mm);
                    this.Message = "Email sent sucessfully.";
                }
            }
            return Page();
        }
    }
}

VisionRestaurant/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace VisionRestaurant.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VisionRestaurant/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisionRestaurant.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

VisionRestaurant/Pages/Menu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using VisionRestaurant.Data;
using VisionRestaurant.Model;
using Microsoft.AspNetCore.Identity;

namespace VisionRestaurant.Pages
{
    public class MenuModel : PageModel
    {
        private readonly VisionRestaurant.Data.VisionRestaurantContext _context;
        private readonly VisionRestaurant.Data.VisionRestaurantContext _db;

        private readonly UserManager<ApplicationUser> _userManager;

        public MenuModel(VisionRestaurant.Data.VisionRestaurantContext context,VisionRestaurantContext db,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _db = db;
            _userManager = userManager;

        }

        public IList<Food> Food { get; set; } = default!;
        public async Task OnGetAsync()
        {
            if (_context.Food != null)
            {
                Food = await _context.Food.ToListAsync();
            }
        }
        public async Task<IActionResult> OnPostBuyAsync(int itemID)
        {
            var user = await _userManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db
            .CheckoutCustomers
            .FindAsync(user.Email);

            var item = _db.BasketItems.FromSqlRaw("SELECT * FROM BasketItems WHERE ID = {0}" + " AND BasketID = {1}", itemID, customer.BasketID)
                        .ToList()
                        .FirstOrDefault();

            if (item == null)
            {
                BasketItem newItem = new BasketItem
                {
                    BasketID = customer.BasketID,
                    ID = itemID,
                    Quantity = 1
                };
                _db.BasketItems.Add(newItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                item.Quantity = item.Quantity + 1;
                _db.Attach(item).State = EntityState.Modified;
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw new Exception($"Basket not found!", e);
                }
            }
            return RedirectToPage();



        }

    }
}

VisionRestaurant/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisionRestaurant.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

VisionRestaurant/Pages/UploadImage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisionRestaurant.Pages
{
    public class UploadImageModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHostEnvironment _environment;

        [BindProperty]
        public IFormFile UploadedFile { get; set; }

        public UploadImageModel(ILogger<IndexModel> logger, IHostEnvironment environment)
        {
            _logger = logger;
            _environment = environment;
        }
        public void OnGet()
        {
        }
        public async Task OnPostAsync()
        {
            if (UploadedFile == null || UploadedFile.Length == 0)
            {
                return;
            }

            _logger.LogInformation($"Uploading {UploadedFile.FileName}.");
            var id = Request.Query["id"];
            string extension = Path.GetExtension(UploadedFile.FileName);
            string newFileName = id + extension;
            string targetFileName = $"{_environment.ContentRootPath}/wwwroot/Image/{newFileName}";

            using (var stream = new FileStream(targetFileName, FileMode.Create))
            {
                await UploadedFile.CopyToAsync(stream);
            }
        }
    }
}

VisionRestaurant/Pages/Checkout.cshtml
@page
@model VisionRestaurant.Pages.CheckoutModel
@{
	ViewData["Title"] = "Checkout";
	
}
@using VisionRestaurant.Data
@using Microsoft.Extensions.Options
@inject IOptions<StripeSettings> Stripe

<h1>Checkout</h1>
<form asp-route-amount="@Model.AmountPayable" method="post">
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th></th>
                <th>Subtotal</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Items)
            {
                var subtotal = item.Price * item.Quantity;
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price.ToString("C")</td>

                    <td>
                        <button type="submit">+</button>
                        <button type="submit">-</button>
                    </td>
                    <td>@item.Quantity</td>
                    <td>@subtotal.ToString("C")</td>
                </tr>
            }
        </tbody>
    </table>
    <div>Total = @Model.Total.ToString("C")</div>
    <button type="submit" asp-page-handler="Buy">Buy</button>
</form>

VisionRestaurant/Pages/Contact.cshtml
@page
@model VisionRestaurant.Pages.ContactModel
@{
	ViewData["Title"] = "Contact";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.6.4.min.js" type="text/javascript"></script>
</head>
<body>
    <form method="post">
        <table border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td style="width: 80px">Name:</td>
                <td><input type="text" name="Name" /></td>
            </tr>
            <tr>
                <td>Subject:</td>
                <td><input type="text" name="Subject" /></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><input type="text" name="Email" /></td>
            </tr>
            <tr>
                <td valign="top">Body:</td>
                <td><textarea cols="20" rows="10" name="Body"></textarea></td>
            </tr>

            <tr>
                <td></td>
                <td><input type="submit" value="Send" asp-page-handler="Submit" /></td>
            </tr>
        </table>
        <br />
        <span style="color:green">@Model.Message</span>
    </form>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.0.20/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({ selector: 'textarea', width: 300 });
    </script>

</body>
</html>

VisionRestaurant/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<link rel="stylesheet" href="~/css/index.css" asp-append-version="true"/>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@using VisionRestaurant.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<h2>Welcome to Vision Restaurant</h2>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
        <h2>Hello @UserManager.GetUserName(User)</h2>
        if (User.IsInRole("Administrator"))
        {
            <h2>Admin Panel</h2>
            <a class="admin nav" asp-area="" asp-page="/Foods/Index">Food Menu Editing</a>
            
        }
    }

    <img src="~/image/bg1.png" class="cookchef"/>
    <div class="desc">
        <p>This is the restaurant that does not exists but this is the right place to dine in.</p>
    </div>
    

</body>

VisionRestaurant/Pages/Menu.cshtml
@page
@model VisionRestaurant.Pages.MenuModel
@{
	ViewData["Title"] = "Menu";
	<h1>The Menu</h1>

}
<form method="post">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Food[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Food[0].Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Food[0].Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Food)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            @{
                var imagepath = @"image\" + item.ID + ".png";
            }
            <td>
                <img src="@imagepath">
            </td>
                <td>
                    <button type="submit" asp-page-handler="Buy"
                        asp-route-itemID="@item.ID">
                        Buy
                    </button>
                </td>


        </tr>
}
    </tbody>
</table>
</form>

VisionRestaurant/Pages/UploadImage.cshtml
@page
@model VisionRestaurant.Pages.UploadImageModel
@{
	ViewData["Title"] = "Upload File";
}

<div class="text-center">
    <h1>Upload File</h1>
</div>

<form method="post" enctype="multipart/form-data">
    <input asp-for="UploadedFile" />
    <input type="submit" />
</form>